---
- hosts: all
  remote_user: centos

  tasks:
    - name: Disable SELinux
      become: true
      selinux:
        state: disabled

    - name: Install Nginx rpm
      become: true
      yum:
        name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
        state: present

    - name: Install Nginx
      become: true
      yum:
        name: nginx-1.14.0
        state: present

    - name: Install MySQL client
      become: true
      yum:
        name: mysql
        state: present

    # Set up client
    - name: Download node installer
      become: true
      get_url:
        url: https://rpm.nodesource.com/setup_8.x
        dest: /tmp/node-installer.sh
        mode: 0700

    - name: Execute node installer
      become: true
      become_user: root
      shell: /tmp/node-installer.sh

    - name: Remove node installer
      become: true
      file: path=/tmp/node-installer.sh state=absent

    - name: Install nodejs
      become: true
      yum:
        name: nodejs
        state: present

    - name: Install package.json dependencies for client
      become: true
      npm:
        path: /vagrant/client
        executable: /usr/bin/npm
        state: present

    - name: Deploy client
      become: true
      shell: npm run build
      args:
        chdir: /vagrant/client

    # Set up server
    - name: Enable epel repository
      become: true
      yum:
        name: epel-release
        state: present

    - name: Install python3 and tools
      become: true
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - python36
        - python36-setuptools
        - mariadb-devel
        - "@Development Tools"
        - python36-devel

    - name: Install pip3
      become: true
      shell: easy_install-3.6 pip

    - name: Install backend app dependencies
      become: true
      shell: /usr/local/bin/pip3 install -r requirements.txt
      args:
        chdir: /vagrant/server

    - name: Configure db access settings
      become: true
      copy:
        src: "../my.cnf"
        dest: /etc/my.cnf.d/
        mode: 0644

    - name: Set up environment
      shell: source ./.env-production && ./scripts/configure
      args:
        chdir: /vagrant/server 

    - name: Run HTTP backend server
      shell: source ./.env-production && APP_ENV=prod PORT=8000 DATABASE_URL="$DATABASE_URL" gunicorn manage:app & disown
      args:
        chdir: /vagrant/server

    # nginx configs
    - name: Copy virtual host files
      become: true
      copy:
        src: "./files/nginx/{{item}}.conf"
        dest: /etc/nginx/conf.d/
      with_items:
        - default
        - amazonaws1.com
        - amazonaws2.com

    - name: Restart Services
      become: true
      service:
        name: "{{item}}"
        state: restarted
      with_items:
        - nginx

    # set up codedeploy agent
    - name: Install agent dependencies
      become: true
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - ruby
        - wget

    - name: Download and run installer script
      become: true
      shell: "{{item}}"
      args:
        chdir: /home/centos
      with_items:
        - source /vagrant/.env && wget https://${AWS_BUCKET_NAME}.s3.amazonaws.com/latest/install && chmod +x ./install
        - ./install auto
